2023-06-12 19:01:59,336 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/ArticleMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,title,author,des,content,type,difficult_level,stars,difficult,create_time  FROM tb_article           ORDER BY id DESC LIMIT ?,?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
2023-06-12 19:01:59,336 [http-nio-8080-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/ArticleMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,title,author,des,content,type,difficult_level,stars,difficult,create_time  FROM tb_article           ORDER BY id DESC LIMIT ?,?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
2023-06-12 19:14:25,823 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/ArticleMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,title,author,des,content,type,stars,difficult,create_time,lastedit  FROM tb_article           ORDER BY id DESC LIMIT ?,?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
2023-06-12 19:14:25,823 [http-nio-8080-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/ArticleMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,title,author,des,content,type,stars,difficult,create_time,lastedit  FROM tb_article           ORDER BY id DESC LIMIT ?,?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
2023-06-12 19:14:38,252 [http-nio-8080-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/ArticleMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,title,author,des,content,type,stars,difficult,create_time,lastedit  FROM tb_article           ORDER BY id DESC LIMIT ?,?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
2023-06-12 19:14:38,255 [http-nio-8080-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/ArticleMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,title,author,des,content,type,stars,difficult,create_time,lastedit  FROM tb_article           ORDER BY id DESC LIMIT ?,?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
2023-06-12 19:15:02,228 [http-nio-8080-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/ArticleMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,title,author,des,content,type,stars,difficult,create_time,lastedit  FROM tb_article           ORDER BY id DESC LIMIT ?,?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
2023-06-12 19:15:02,228 [http-nio-8080-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/ArticleMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,title,author,des,content,type,stars,difficult,create_time,lastedit  FROM tb_article           ORDER BY id DESC LIMIT ?,?
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'field list'
2023-06-12 22:13:22,052 [http-nio-8080-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:38 - 全局异常, 请先完善七牛云服务配置，再进行操作
2023-06-12 23:34:20,742 [http-nio-8080-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-12 23:34:20,755 [http-nio-8080-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-12 23:34:23,989 [http-nio-8080-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-12 23:34:24,295 [http-nio-8080-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-12 23:34:25,102 [http-nio-8080-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-12 23:34:25,426 [http-nio-8080-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:12,241 [http-nio-8080-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:12,241 [http-nio-8080-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:32,159 [http-nio-8080-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:32,520 [http-nio-8080-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:33,072 [http-nio-8080-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:33,378 [http-nio-8080-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:34,114 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:34,431 [http-nio-8080-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:42,360 [http-nio-8080-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:42,360 [http-nio-8080-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:55,548 [http-nio-8080-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:05:55,854 [http-nio-8080-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:10:26,261 [http-nio-8080-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 00:10:26,261 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 08:38:27,439 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 08:38:27,439 [http-nio-8080-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 08:51:24,603 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 08:51:24,917 [http-nio-8080-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-13 08:51:28,926 [http-nio-8080-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 08:51:29,236 [http-nio-8080-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-13 08:52:20,990 [http-nio-8080-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 08:52:21,295 [http-nio-8080-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-13 08:52:21,787 [http-nio-8080-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 08:52:22,103 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-13 08:52:38,399 [http-nio-8080-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 10:24:04,473 [restartedMain] ERROR [com.baomidou.mybatisplus.core.MybatisConfiguration] MybatisConfiguration.java:84 - mapper[cn.tycoding.biz.mapper.ProblemTagMapper.findByProblemId] is ignored, because it exists, maybe from xml file
2023-06-13 10:27:34,194 [http-nio-8080-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 10:52:12,744 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 10:52:15,848 [http-nio-8080-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 13:58:13,183 [http-nio-8080-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 13:58:17,628 [http-nio-8080-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 13:58:18,753 [http-nio-8080-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 13:58:20,088 [http-nio-8080-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 14:27:00,562 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 15:05:03,862 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 15:05:07,550 [http-nio-8080-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 16:06:32,774 [http-nio-8080-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 16:17:08,264 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 17:21:36,599 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 17:21:39,204 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 17:31:06,216 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 18:58:45,468 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 19:06:17,357 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 19:39:20,081 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 22:02:03,614 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 22:09:25,225 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required Long parameter 'pid' is not present
2023-06-13 22:23:27,209 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required Long parameter 'pid' is not present
2023-06-13 22:23:38,834 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required Long parameter 'pid' is not present
2023-06-13 22:24:29,219 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required Long parameter 'pid' is not present
2023-06-13 22:25:02,171 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required Long parameter 'pid' is not present
2023-06-13 22:25:32,079 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required Long parameter 'pid' is not present
2023-06-13 22:30:06,461 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required Long parameter 'pid' is not present
2023-06-13 22:30:14,049 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required Long parameter 'pid' is not present
2023-06-13 22:31:54,314 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required Long parameter 'pid' is not present
2023-06-13 22:35:02,622 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 22:57:55,291 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-13 23:41:47,130 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.list(cn.tycoding.biz.entity.Category)
2023-06-13 23:44:08,844 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.list(cn.tycoding.biz.entity.Category)
2023-06-13 23:44:47,116 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.list(cn.tycoding.biz.entity.Category)
2023-06-14 00:13:32,101 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-14 00:15:25,820 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-14 00:16:52,690 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-14 00:20:38,981 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-14 00:48:39,123 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "undefined"
2023-06-14 00:50:31,010 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "undefined"
2023-06-14 01:31:30,490 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-14 01:31:48,245 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.selectAllWithTree(cn.tycoding.biz.entity.Category)
2023-06-14 01:35:48,014 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.selectAllWithTree(cn.tycoding.biz.entity.Category)
2023-06-14 01:35:50,814 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.selectAllWithTree(cn.tycoding.biz.entity.Category)
2023-06-14 01:37:54,672 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.selectAllWithTree(cn.tycoding.biz.entity.Category)
2023-06-14 01:38:39,628 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.selectAllWithTree(cn.tycoding.biz.entity.Category)
2023-06-14 01:38:42,899 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.selectAllWithTree(cn.tycoding.biz.entity.Category)
2023-06-14 01:40:58,205 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.selectAllWithTree(cn.tycoding.biz.entity.Category)
2023-06-14 01:49:03,690 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.selectAllWithTree(cn.tycoding.biz.entity.Category)
2023-06-14 01:54:20,416 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-14 01:54:25,941 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-14 01:57:11,570 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-14 02:05:10,103 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-14 08:16:07,674 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-14 09:57:03,223 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 13:12:26,093 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 13:12:38,126 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 13:13:16,608 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 13:13:23,720 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 13:14:28,195 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 13:14:32,349 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 13:14:38,821 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 13:14:41,289 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 13:14:44,448 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 14:54:51,467 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 14:54:54,868 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 18:04:03,276 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 18:04:05,400 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 18:04:06,666 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 18:04:07,677 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 18:04:08,458 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 18:04:09,314 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 18:04:10,377 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 18:04:11,175 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-15 19:59:52,006 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.list(cn.tycoding.biz.entity.Category)
2023-06-15 20:03:02,205 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.list(cn.tycoding.biz.entity.Category)
2023-06-15 20:04:00,319 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.list(cn.tycoding.biz.entity.Category)
2023-06-15 20:04:03,149 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.CategoryController.list(cn.tycoding.biz.entity.Category)
2023-06-16 00:08:12,397 [restartedMain] ERROR [org.springframework.boot.SpringApplication] SpringApplication.java:837 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiroFilterFactoryBean' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizationAttributeSourceAdvisor' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: Unsatisfied dependency expressed through method 'authorizationAttributeSourceAdvisor' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityManager' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: Unsatisfied dependency expressed through method 'securityManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authRealm': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [E:\repository\DBproject\api\target\classes\cn\tycoding\biz\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [E:\repository\DBproject\api\target\classes\mapper\ProblemCategoryMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 14; 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:241)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:723)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at cn.tycoding.TumoApplication.main(TumoApplication.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizationAttributeSourceAdvisor' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: Unsatisfied dependency expressed through method 'authorizationAttributeSourceAdvisor' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityManager' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: Unsatisfied dependency expressed through method 'securityManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authRealm': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [E:\repository\DBproject\api\target\classes\cn\tycoding\biz\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [E:\repository\DBproject\api\target\classes\mapper\ProblemCategoryMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 14; 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:111)
	at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:92)
	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:101)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:251)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1141)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1114)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:506)
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityManager' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: Unsatisfied dependency expressed through method 'securityManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authRealm': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [E:\repository\DBproject\api\target\classes\cn\tycoding\biz\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [E:\repository\DBproject\api\target\classes\mapper\ProblemCategoryMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 14; 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
	... 37 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authRealm': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [E:\repository\DBproject\api\target\classes\cn\tycoding\biz\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [E:\repository\DBproject\api\target\classes\mapper\ProblemCategoryMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 14; 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
	... 51 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [E:\repository\DBproject\api\target\classes\cn\tycoding\biz\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [E:\repository\DBproject\api\target\classes\mapper\ProblemCategoryMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 14; 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 65 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [E:\repository\DBproject\api\target\classes\cn\tycoding\biz\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [E:\repository\DBproject\api\target\classes\mapper\ProblemCategoryMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 14; 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1526)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 78 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [E:\repository\DBproject\api\target\classes\mapper\ProblemCategoryMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 14; 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1511)
	... 89 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [E:\repository\DBproject\api\target\classes\mapper\ProblemCategoryMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 14; 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
	... 102 common frames omitted
Caused by: org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [E:\repository\DBproject\api\target\classes\mapper\ProblemCategoryMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 14; 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:593)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBean.java:429)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.getObject(MybatisSqlSessionFactoryBean.java:626)
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration.sqlSessionFactory(MybatisPlusAutoConfiguration.java:215)
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$2ed4f82d.CGLIB$sqlSessionFactory$1(<generated>)
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$2ed4f82d$$FastClassBySpringCGLIB$$2fdaca4b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$2ed4f82d.sqlSessionFactory(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 103 common frames omitted
Caused by: org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 14; 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at org.apache.ibatis.parsing.XPathParser.createDocument(XPathParser.java:263)
	at org.apache.ibatis.parsing.XPathParser.<init>(XPathParser.java:127)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.<init>(XMLMapperBuilder.java:81)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:590)
	... 116 common frames omitted
Caused by: org.xml.sax.SAXParseException: 元素类型为 "select" 的内容必须匹配 "(include|trim|where|set|foreach|choose|if|bind)"。
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleEndElement(XMLDTDValidator.java:1996)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.endElement(XMLDTDValidator.java:881)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2969)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:507)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:867)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:796)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:142)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:247)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at org.apache.ibatis.parsing.XPathParser.createDocument(XPathParser.java:261)
	... 119 common frames omitted
2023-06-16 00:50:19,474 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 00:50:22,043 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 00:50:41,806 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:51:31,580 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:53:42,791 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:54:32,251 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:56:43,213 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:56:45,899 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:58:01,272 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:58:04,795 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:58:53,218 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:58:54,406 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:58:54,902 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:59:26,913 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 00:59:27,606 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'problemCategory' for method parameter of type ProblemCategory
2023-06-16 01:00:50,710 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 01:04:48,129 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 01:06:51,782 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 01:07:43,610 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:08:33,633 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:09:16,114 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:09:19,086 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:09:26,915 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:20:52,404 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:20:53,886 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:20:55,154 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:20:59,908 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:21:14,881 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:21:15,511 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:21:16,672 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:21:17,185 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:21:18,172 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:23:16,874 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:25:47,976 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:35:02,605 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:37:41,118 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:41:28,228 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:41:57,768 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:42:13,108 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:46:07,246 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:46:08,730 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:51:29,627 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:51:33,646 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:52:20,488 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Required request body is missing: public cn.tycoding.common.utils.R cn.tycoding.biz.controller.ProblemController.list(cn.tycoding.biz.entity.Problem,cn.tycoding.common.utils.QueryPage)
2023-06-16 01:52:36,649 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:52:41,018 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:53:04,267 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:53:15,214 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:54:08,630 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 01:54:22,689 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'id' for method parameter of type Long
2023-06-16 01:54:26,103 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'id' for method parameter of type Long
2023-06-16 01:54:30,154 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Missing URI template variable 'id' for method parameter of type Long
2023-06-16 02:05:07,225 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 08:20:18,987 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 08:47:00,134 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 08:48:18,952 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 08:49:06,339 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 08:51:08,831 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'GET' not supported
2023-06-16 08:56:13,309 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 08:56:41,687 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Invalid bound statement (not found): cn.tycoding.biz.mapper.ProblemMapper.findByCategoryPage
2023-06-16 08:58:30,686 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Invalid bound statement (not found): cn.tycoding.biz.mapper.ProblemMapper.findByCategoryPage
2023-06-16 08:59:22,798 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, nested exception is org.apache.ibatis.binding.BindingException: Parameter 'ew' not found. Available parameters are [wrapper, page, param1, param2]
2023-06-16 09:02:35,693 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 09:02:49,911 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, nested exception is org.apache.ibatis.binding.BindingException: Parameter 'ew' not found. Available parameters are [wrapper, page, param1, param2]
2023-06-16 09:06:47,902 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, nested exception is org.apache.ibatis.binding.BindingException: Parameter 'ew' not found. Available parameters are [wrapper, page, param1, param2]
2023-06-16 09:11:17,355 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, nested exception is org.apache.ibatis.binding.BindingException: Parameter 'ew' not found. Available parameters are [wrapper, page, param1, param2]
2023-06-16 09:18:50,078 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 09:18:54,021 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 09:47:54,148 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 10:11:10,000 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 10:14:46,229 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 10:14:59,024 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 10:15:21,758 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 10:15:24,446 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 10:15:44,420 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 10:16:31,113 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 10:51:12,720 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 10:51:12,804 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 10:51:55,582 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 10:51:59,131 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 13:25:41,839 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 13:26:48,073 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 13:30:20,040 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, null
2023-06-16 13:30:20,040 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:34:01,129 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:34:01,129 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:34:05,680 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:34:05,680 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:35:00,676 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:35:00,994 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:35:44,923 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:35:45,238 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:36:19,304 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:36:19,304 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:36:49,856 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:36:58,580 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:37:08,892 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:37:13,117 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:37:32,551 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:37:40,188 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:37:46,103 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:37:46,103 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:38:24,737 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:38:24,737 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:38:28,242 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:38:28,242 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:39:40,128 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:39:40,128 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:39:46,777 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:39:46,777 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:40:14,647 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:40:14,647 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:41:23,504 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:41:23,504 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:52:26,758 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:52:26,758 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:52:37,521 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:52:37,824 [http-nio-8082-exec-3] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:53:41,334 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:53:41,335 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:54:54,255 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:54:54,255 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:55:06,485 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 13:55:06,785 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Request method 'POST' not supported
2023-06-16 21:35:11,824 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "null"
2023-06-16 21:36:01,613 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT p.* FROM problem p
        WHERE p.id IN
        (  
        SELECT p.id
        FROM pblm_catg pc, problem p where 1 = 1
         WHERE  category_id = ? and p.id = pc.problem_id 
      ) ) TOTAL 

### The error may exist in file [E:\repository\DBproject\api\target\classes\mapper\ProblemMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT p.* FROM problem p
        WHERE p.id IN
        (  
        SELECT p.id
        FROM pblm_catg pc, problem p where 1 = 1
         WHERE  category_id = ? and p.id = pc.problem_id 
      ) ) TOTAL 

2023-06-17 01:04:59,662 [http-nio-8082-exec-10] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT p.*
        FROM problem p
        WHERE 1==1
             
                and p.uid = ? ) TOTAL 

### The error may exist in file [E:\repository\DBproject\api\target\classes\mapper\ProblemMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT p.*
        FROM problem p
        WHERE 1==1
             
                and p.uid = ? ) TOTAL 

2023-06-17 01:13:16,087 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT p.*
        FROM problem p
        WHERE 1==1
         
                and p.uid = ? ) TOTAL 

### The error may exist in file [E:\repository\DBproject\api\target\classes\mapper\ProblemMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT p.*
        FROM problem p
        WHERE 1==1
         
                and p.uid = ? ) TOTAL 

2023-06-17 01:13:27,518 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT p.*
        FROM problem p
        WHERE 1==1
         
                and p.uid = ? ) TOTAL 

### The error may exist in file [E:\repository\DBproject\api\target\classes\mapper\ProblemMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Error: Method queryTotal execution error of sql : 
 SELECT COUNT(1) FROM ( SELECT p.*
        FROM problem p
        WHERE 1==1
         
                and p.uid = ? ) TOTAL 

2023-06-17 02:00:06,841 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/OrganizationMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,uid,pid,name  FROM organization     WHERE (uid = ?) ORDER BY id DESC
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
2023-06-17 02:02:18,399 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/OrganizationMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,uid,pid,name  FROM organization     WHERE (uid = ?) ORDER BY id DESC
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
2023-06-17 02:02:26,130 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/OrganizationMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,uid,pid,name  FROM organization     WHERE (uid = ?) ORDER BY id DESC
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
2023-06-17 02:02:58,603 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/OrganizationMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,uid,pid,name  FROM organization     WHERE (uid = ?) ORDER BY id DESC
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
2023-06-17 02:06:09,943 [http-nio-8082-exec-9] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/OrganizationMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,uid,pid,name  FROM organization     WHERE (uid = ?) ORDER BY id DESC
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
2023-06-17 02:06:39,536 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, 
### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
### The error may exist in cn/tycoding/biz/mapper/OrganizationMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT  id,uid,pid,name  FROM organization     WHERE (uid = ?) ORDER BY id DESC
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'pid' in 'field list'
2023-06-17 11:22:46,213 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Invalid bound statement (not found): cn.tycoding.biz.mapper.ProblemMapper.findByPositionPage
2023-06-17 11:23:42,382 [http-nio-8082-exec-4] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Invalid bound statement (not found): cn.tycoding.biz.mapper.ProblemMapper.findByPositionPage
2023-06-17 11:24:46,259 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:31 - 内部错误, Invalid bound statement (not found): cn.tycoding.biz.mapper.ProblemMapper.findByPositionPage
2023-06-17 11:47:18,249 [restartedMain] ERROR [org.springframework.boot.SpringApplication] SpringApplication.java:837 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiroFilterFactoryBean' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizationAttributeSourceAdvisor' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: Unsatisfied dependency expressed through method 'authorizationAttributeSourceAdvisor' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'securityManager' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shiro.mgt.SecurityManager]: Factory method 'securityManager' threw exception; nested exception is org.apache.shiro.cache.CacheException: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: InputStreamConfigurationSource [stream=sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@2d564989]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:241)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:723)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at cn.tycoding.TumoApplication.main(TumoApplication.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authorizationAttributeSourceAdvisor' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: Unsatisfied dependency expressed through method 'authorizationAttributeSourceAdvisor' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'securityManager' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shiro.mgt.SecurityManager]: Factory method 'securityManager' threw exception; nested exception is org.apache.shiro.cache.CacheException: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: InputStreamConfigurationSource [stream=sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@2d564989]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:797)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:207)
	at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:91)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:111)
	at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:92)
	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:101)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:251)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1141)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:1114)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:506)
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'securityManager' defined in class path resource [cn/tycoding/common/auth/ShiroConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shiro.mgt.SecurityManager]: Factory method 'securityManager' threw exception; nested exception is org.apache.shiro.cache.CacheException: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: InputStreamConfigurationSource [stream=sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@2d564989]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1304)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1224)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788)
	... 37 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.shiro.mgt.SecurityManager]: Factory method 'securityManager' threw exception; nested exception is org.apache.shiro.cache.CacheException: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: InputStreamConfigurationSource [stream=sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@2d564989]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
	... 51 common frames omitted
Caused by: org.apache.shiro.cache.CacheException: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: InputStreamConfigurationSource [stream=sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@2d564989]
	at org.apache.shiro.cache.ehcache.EhCacheManager.ensureCacheManager(EhCacheManager.java:223)
	at org.apache.shiro.cache.ehcache.EhCacheManager.getCache(EhCacheManager.java:155)
	at org.apache.shiro.realm.AuthorizingRealm.getAuthorizationCacheLazy(AuthorizingRealm.java:246)
	at org.apache.shiro.realm.AuthorizingRealm.getAvailableAuthorizationCache(AuthorizingRealm.java:261)
	at org.apache.shiro.realm.AuthorizingRealm.afterCacheManagerSet(AuthorizingRealm.java:227)
	at org.apache.shiro.realm.CachingRealm.setCacheManager(CachingRealm.java:96)
	at org.apache.shiro.mgt.RealmSecurityManager.applyCacheManagerToRealms(RealmSecurityManager.java:118)
	at org.apache.shiro.mgt.RealmSecurityManager.afterCacheManagerSet(RealmSecurityManager.java:157)
	at org.apache.shiro.mgt.SessionsSecurityManager.afterCacheManagerSet(SessionsSecurityManager.java:107)
	at org.apache.shiro.mgt.CachingSecurityManager.setCacheManager(CachingSecurityManager.java:83)
	at cn.tycoding.common.auth.ShiroConfig.securityManager(ShiroConfig.java:55)
	at cn.tycoding.common.auth.ShiroConfig$$EnhancerBySpringCGLIB$$6fec8c95.CGLIB$securityManager$0(<generated>)
	at cn.tycoding.common.auth.ShiroConfig$$EnhancerBySpringCGLIB$$6fec8c95$$FastClassBySpringCGLIB$$c0c7659a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at cn.tycoding.common.auth.ShiroConfig$$EnhancerBySpringCGLIB$$6fec8c95.securityManager(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 52 common frames omitted
Caused by: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: InputStreamConfigurationSource [stream=sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@2d564989]
	at net.sf.ehcache.CacheManager.assertNoCacheManagerExistsWithSameName(CacheManager.java:529)
	at net.sf.ehcache.CacheManager.init(CacheManager.java:374)
	at net.sf.ehcache.CacheManager.<init>(CacheManager.java:339)
	at org.apache.shiro.cache.ehcache.EhCacheManager.ensureCacheManager(EhCacheManager.java:212)
	... 72 common frames omitted
2023-06-17 20:09:36,581 [restartedMain] ERROR [com.zaxxer.hikari.pool.HikariPool] HikariPool.java:593 - HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:324)
	at org.springframework.boot.jdbc.EmbeddedDatabaseConnection.isEmbedded(EmbeddedDatabaseConnection.java:120)
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateDefaultDdlAutoProvider.getDefaultDdlAuto(HibernateDefaultDdlAutoProvider.java:42)
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration.lambda$getVendorProperties$1(HibernateJpaConfiguration.java:130)
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateSettings.getDdlAuto(HibernateSettings.java:41)
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.determineDdlAuto(HibernateProperties.java:136)
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.getAdditionalProperties(HibernateProperties.java:102)
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateProperties.determineHibernateProperties(HibernateProperties.java:94)
	at org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaConfiguration.getVendorProperties(HibernateJpaConfiguration.java:132)
	at org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration.entityManagerFactory(JpaBaseConfiguration.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:635)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at cn.tycoding.TumoApplication.main(TumoApplication.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
2023-06-17 20:09:37,885 [task-1] ERROR [com.zaxxer.hikari.pool.HikariPool] HikariPool.java:593 - HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:176)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:118)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1224)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1255)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:391)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2023-06-17 20:17:48,227 [http-nio-8082-exec-5] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:38 - 全局异常, null
2023-06-17 20:17:54,415 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:38 - 全局异常, null
2023-06-17 20:24:18,283 [http-nio-8082-exec-1] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:38 - 全局异常, null
2023-06-17 20:44:15,124 [http-nio-8082-exec-8] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:38 - 全局异常, null
2023-06-17 20:55:47,644 [http-nio-8082-exec-2] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:38 - 全局异常, null
2023-06-17 20:57:45,576 [http-nio-8082-exec-6] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:38 - 全局异常, null
2023-06-17 20:58:09,495 [http-nio-8082-exec-7] ERROR [cn.tycoding.common.handler.GlobalExceptionHandler] GlobalExceptionHandler.java:38 - 全局异常, null
